### ISSUE TITLE
[Design] - Links are missing active / pressed state.

### ISSUE THREAD

**Issue by minimalsm** [ethereum/geth-website#89]
![image](https://user-images.githubusercontent.com/62268199/205052418-7dd2bfee-49a6-4eef-bc00-1c9812eea7f6.png)

**Comment by nloureiro** [comment]
the :hover state is on this issue
https://github.com/ethereum/geth-website/issues/73

but the I forgot to add the 

:focus
![Screen Shot 2022-12-02 10 07 22 AM](https://user-images.githubusercontent.com/1120748/205268511-b5a5683e-92ff-47cd-af64-28db563d7553.png)



and the :active
![Screen Shot 2022-12-02 10 03 54 AM](https://user-images.githubusercontent.com/1120748/205268537-6e1e6cf4-fe73-4371-a974-edaf58ed17e2.png)

**Comment by wackerow** [comment]
@minimalsm Were you referring to the links within the body of the docs here? Or the DocumentNav on the right?

@nloureiro You've alluded to the DocumentNav on the right, which has been fixed in #107, but @nhsz raised some confusion around if this issue is looking to fix the `active` and `focus` states for the links within the body. 

In either case, as I look at it closer, we do need to fix the active and focus states for generic links, so I'll mark #107 as _not_ closing this issue, and I'll address this separately.

**Comment by minimalsm** [comment]
@wackerow I was referring to body links specifically
